CREATE TABLE `TB_MZ_LIST_RESTAURANT_REL`
(
    `RESTAURANT_ID` VARCHAR(36) COMMENT '음식점 아이디',
    `LIST_ID` VARCHAR(36) COMMENT '리스트 아이디',
    PRIMARY KEY (RESTAURANT_ID, LIST_ID)
) COMMENT = '맛집 리스트 음식점 관계 테이블'
;