CREATE TABLE `TB_MZ_LIST_RESTAURANT_REL`
(
    `RESTAURANT_LIST_REL_ID` VARCHAR(36) PRIMARY KEY COMMENT '음식점 리스트 관계 아이디',
    `RESTAURANT_ID` VARCHAR(36) COMMENT '음식점 아이디',
    `LIST_ID` VARCHAR(36) COMMENT '리스트 아이디'
) COMMENT = '맛집 리스트 음식점 관계 테이블'
;