CREATE TABLE `TB_MZ_LIST`
(
    `LIST_ID` VARCHAR(36) PRIMARY KEY COMMENT '리스트 아이디',
    `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자 아이디',
    `LIST_NAME` VARCHAR(50) NOT NULL COMMENT '리스트 이름',
    `CREATED_DATE` VARCHAR(8) NOT NULL COMMENT '생성일자'
) COMMENT = '맛집 리스트 테이블'
;