CREATE TABLE `TB_USER`
(
    `USER_ID` VARCHAR(20) PRIMARY KEY COMMENT '사용자 아이디',
    `USER_NAME` VARCHAR(30) NOT NULL COMMENT '사용자 이름',
    `PASSWORD` VARCHAR(30) NOT NULL COMMENT '비밀번호',
    `BIRTH_DATE` VARCHAR(8) NOT NULL COMMENT '생년월일(YYYYMMDD)',
    `GENDER` VARCHAR(1) NOT NULL COMMENT '성별(M-male/F-Female)',
    `ACTIVE_YN` VARCHAR(1) NOT NULL COMMENT '계정 활성화 여부(Y/N)'
) COMMENT = '사용자 테이블'
;