CREATE TABLE `TB_RESTAURANT`
(
    `RESTAURANT_ID` VARCHAR(36) PRIMARY KEY COMMENT '음식점 아이디',
    `RESTAURANT_NAME` VARCHAR(30) NOT NULL COMMENT '사용자 이름',
    `RESTAURANT_ADDRESS` VARCHAR(200) NOT NULL COMMENT '음식점 주소',
    `RESTAURANT_CATEGORY` VARCHAR(8) NOT NULL COMMENT '음식점 카테고리',
    `OPERATION_YN` VARCHAR(1) NOT NULL COMMENT '음식점 영업 여부(Y/N)'
) COMMENT = '음식점 테이블'
;